import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, Mail, RefreshCw, ShieldCheck, Info, Copy } from 'lucide-react';
import { toast } from 'react-toastify';
import { checkAllServices } from '@/api/apiEndpoints';
import { useAuth } from '../../context/AuthContext';

const POLL_INTERVAL_MS = 30000;
const INCLUDE_PYTHON_UPTIME =
  String(import.meta.env.VITE_UPTIME_CHECK_PYTHON || 'false').toLowerCase() === 'true';

const createMailtoLink = (recipient, subject, body) => {
  const params = new URLSearchParams({ subject, body }).toString();
  return `mailto:${encodeURIComponent(recipient)}?${params}`;
};

const formatServiceErrors = (details) => {
  const errors = [];

  if (details?.python?.enabled && !details.python.healthy) {
    errors.push(`Python backend: ${details.python.error || 'unreachable'}`);
  }

  if (details?.csharp?.enabled && !details.csharp.healthy) {
    errors.push(`C# auth service: ${details.csharp.error || 'unreachable'}`);
  }

  return errors.length > 0 ? errors.join(' | ') : 'Service health degraded';
};

function UptimeStatus() {
  const { user } = useAuth();
  const [status, setStatus] = useState('checking');
  const [details, setDetails] = useState(null);
  const [showSetup, setShowSetup] = useState(false);
  const [copied, setCopied] = useState(false);
  const emailSentRef = useRef(false);
  const mountedRef = useRef(true);
  const previousStatusRef = useRef('checking');

  const userEmail = useMemo(() => {
    return user?.email || user?.Email || user?.EmailId || null;
  }, [user]);

  const sendEmailNotification = useCallback(
    (message) => {
      if (!userEmail) return;
      const subject = 'Uptime Alert: Service issue detected';
      const body = `Hello,\n\nAn uptime issue was detected in the frontend monitor.\n\nUser: ${userEmail}\nTime: ${new Date().toISOString()}\n\nDetails:\n${message}\n\nThis email is auto-generated by the frontend uptime monitor.`;
      const mailtoUrl = createMailtoLink(userEmail, subject, body);
      window.location.href = mailtoUrl;
    },
    [userEmail]
  );

  const runHealthCheck = useCallback(async () => {
    try {
      const result = await checkAllServices({ includePython: INCLUDE_PYTHON_UPTIME });
      if (!mountedRef.current) return;

      const healthy = result.csharp.healthy && (!result.python.enabled || result.python.healthy);
      setStatus(healthy ? 'healthy' : 'degraded');
      setDetails(result);

      const nextStatus = healthy ? 'healthy' : 'degraded';
      const wasStatus = previousStatusRef.current;
      previousStatusRef.current = nextStatus;

      if (!healthy && wasStatus !== 'degraded') {
        const errorText = formatServiceErrors(result);
        toast.error(`Uptime issue: ${errorText}`, { autoClose: 6000 });

        if (userEmail && !emailSentRef.current) {
          emailSentRef.current = true;
          sendEmailNotification(errorText);
        }
      } else {
        emailSentRef.current = false;
      }
    } catch (error) {
      if (!mountedRef.current) return;

      const errorText = error?.message || 'Unknown uptime error';
      setStatus('error');
      setDetails({ error: errorText });
      if (previousStatusRef.current !== 'error') {
        toast.error(`Uptime monitor failed: ${errorText}`, { autoClose: 6000 });
      }
      previousStatusRef.current = 'error';

      if (userEmail && !emailSentRef.current) {
        emailSentRef.current = true;
        sendEmailNotification(errorText);
      }
    }
  }, [sendEmailNotification, userEmail]);

  useEffect(() => {
    mountedRef.current = true;
    runHealthCheck();
    const intervalId = window.setInterval(runHealthCheck, POLL_INTERVAL_MS);
    return () => {
      mountedRef.current = false;
      window.clearInterval(intervalId);
    };
  }, [runHealthCheck]);

  const setupText = useMemo(() => {
    return [
      'Uptime Kuma Dashboard: http://localhost:3001',
      'Frontend app URL: http://localhost:5173',
      'Frontend monitor type: HTTP(s) (checks site availability)',
      `Optional backend monitor: http://127.0.0.1:8080/health (${INCLUDE_PYTHON_UPTIME ? 'enabled in app' : 'disabled in app'})`,
      'Optional auth monitor: http://localhost:5224/api/auth/status',
      'Note: Uptime Kuma only checks reachability. JavaScript errors need browser error logging.'
    ].join('\n');
  }, []);

  const copySetupText = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(setupText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error('Copy failed. Please select and copy manually.');
    }
  }, [setupText]);

  const label = useMemo(() => {
    if (status === 'healthy') return 'Uptime OK';
    if (status === 'degraded') return 'Uptime Issue';
    if (status === 'error') return 'Uptime Failed';
    return 'Checking uptime';
  }, [status]);

  const badgeClass = useMemo(() => {
    if (status === 'healthy') return 'bg-emerald-500/15 text-emerald-700 border-emerald-500/30';
    if (status === 'degraded') return 'bg-amber-500/15 text-amber-700 border-amber-500/30';
    if (status === 'error') return 'bg-red-500/15 text-red-700 border-red-500/30';
    return 'bg-slate-500/10 text-slate-700 border-slate-500/20';
  }, [status]);

  const icon = useMemo(() => {
    if (status === 'healthy') return <ShieldCheck className="h-4 w-4" />;
    if (status === 'degraded') return <AlertTriangle className="h-4 w-4" />;
    if (status === 'error') return <AlertTriangle className="h-4 w-4" />;
    return <RefreshCw className="h-4 w-4 animate-spin" />;
  }, [status]);

  return (
    <div className={`relative inline-flex items-center gap-2 rounded-full border px-3 py-1 text-[11px] font-semibold ${badgeClass}`}>
      <div className="flex items-center gap-1">
        {icon}
        <span>{label}</span>
      </div>
      {userEmail && status !== 'healthy' && (
        <button
          type="button"
          onClick={() => sendEmailNotification(formatServiceErrors(details) || 'Service issue detected.')}
          className="inline-flex items-center gap-1 rounded-full bg-white/90 px-2 py-1 text-xs text-slate-700 hover:bg-slate-100 border border-slate-200"
        >
          <Mail className="h-3.5 w-3.5" />
          Report
        </button>
      )}
      <button
        type="button"
        onClick={() => setShowSetup((value) => !value)}
        className="inline-flex items-center gap-1 rounded-full bg-white/90 px-2 py-1 text-xs text-slate-700 hover:bg-slate-100 border border-slate-200"
      >
        <Info className="h-3.5 w-3.5" />
        Setup
      </button>
      {showSetup && (
        <div className="absolute right-0 top-full z-50 mt-2 w-[320px] rounded-2xl border border-slate-700 bg-slate-950 p-4 text-left text-xs text-slate-200 shadow-2xl">
          <div className="flex items-center justify-between gap-2 pb-2 border-b border-slate-700 mb-3">
            <div>
              <p className="font-semibold text-sm">Uptime Kuma Setup</p>
              <p className="text-slate-400">Use these URLs inside Uptime Kuma</p>
            </div>
            <button
              type="button"
              onClick={() => setShowSetup(false)}
              className="text-slate-400 hover:text-white"
            >
              ✕
            </button>
          </div>
          <div className="space-y-2 text-[11px] leading-5">
            <p><span className="font-semibold">Kuma UI:</span> <span className="text-slate-300">http://localhost:3001</span></p>
            <p><span className="font-semibold">Frontend URL:</span> <span className="text-slate-300">http://localhost:5173</span></p>
            <p><span className="font-semibold">Frontend monitor:</span> <span className="text-slate-300">HTTP(s) check</span></p>
            <p className="text-slate-400">This checks app availability only, not JavaScript errors.</p>
            <p className="text-slate-400">If you want backend monitors:</p>
            <ul className="list-disc pl-4 text-slate-300">
              <li>http://127.0.0.1:8080/health</li>
              <li>http://localhost:5224/api/auth/status</li>
            </ul>
          </div>
          <button
            type="button"
            onClick={copySetupText}
            className="mt-4 inline-flex items-center gap-2 rounded-full bg-slate-800 px-3 py-2 text-xs font-semibold text-slate-200 hover:bg-slate-700"
          >
            <Copy className="h-3.5 w-3.5" />
            {copied ? 'Copied' : 'Copy setup text'}
          </button>
        </div>
      )}
    </div>
  );
}

export default UptimeStatus;
